baseURL = "http://lazymonad.com"
languageCode = "en"
title = "Lazy Monad"
theme = "minimal"
enableRobotsTXT = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
canonifyurls = true

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License. See: https://creativecommons.org/licenses/by-nc/4.0/legalcode."

[params]
    author = "Muhammad Umer Azad"
    description = "Personal blog"
    githubUsername = "umerazad"
    accent = "darkgreen"
    showBorder = true
    backgroundColor = "white"
    font = "Inconsolata" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "solarized-dark"
    highlightLanguages = ["rust", "go", "haskell", "c", "c++", "C#", "python"]

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 1

[[menu.main]]
  name = "Tags"
  weight = 2
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:umer@fastmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/umerazad/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/umerazad/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/umerazad/"
    name = "linkedin"
    weight = 4
